### ISSUE TITLE
feat(auth): create register/login flow with google oauth

### ISSUE THREAD

**Issue by tsirlucas** [tsirlucas/PayIt#5]
- [x] feat(auth): create login page #9 
- [x] feat(auth): create router logics to control what user can access #10 
- [x] feat(auth): create user on firebase after register #15
- [x] feat(auth): ask user about payday #16
- [x] feat(auth) store and retrieve user's session #58
