### ISSUE TITLE
feat(bills): create basic bills crud

### ISSUE THREAD

**Issue by tsirlucas** [tsirlucas/PayIt#6]
- [x] feat(bills): create list in bills page #17
- [x] feat(bills): create bills form #18
- [x] feat(bills): create remove bills logics #19
