### ISSUE TITLE
feat(settings): create basic settings page

### ISSUE THREAD

**Issue by tsirlucas** [tsirlucas/PayIt#8]
- [x] feat(settings): show user settings #22 
- [x] feat(settings): user settings edit #23 
- [x] feat(settings): trigger pendencies update when user changes payday #82
